spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port:8081


jwt:
  auth:
    converter:
      resource-id: client
      principal-attribute: preferred_username


keycloak:
  admin:
    url: http://localhost:8080/auth
    realm: myrealm
    client-id: client
    username: shahzaib
    password: 12345678
    token-url: http://localhost:8080/realms/myrealm/protocol/openid-connect/token